language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
before_install:
  - pip install git+https://github.com/pepkit/peppy.git@dev
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-test.txt
script: pytest tests -x -vv --cov=eido
after_success:
  - coveralls
branches:
  only:
    - dev
    - master