site_name: eido
site_url: http://eido.databio.org/
repo_url: http://github.com/pepkit/eido
pypi_name: eido

nav:
  - Getting Started: 
    - Introduction: README.md
    - Install and configure: install.md
  - How-to Guides:
    - "Tutorial: eido in Python": demo.md
    - "Tutorial: eido in a shell": cli.md
  - Reference:
    - Schema specification: schema-specification.md
    - Example schemas: schemas.md
    - Eido Python API: autodoc_build/eido.md
    - Support: https://github.com/pepkit/eido/issues
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "eido"
      no_top_level: true
  - search
